import { ElementTypes, CategoryTypes } from "@/lib/constants";
import type { LucideIcon } from "lucide-react";
import {
  Columns2,
  Columns3,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  Image,
  Link,
  Pilcrow,
  SquareDashed,
  Text,
  Rows,
  LayoutTemplate,
  Layout,
  Grid2x2,
  Grid3x3,
  Sidebar,
  Video,
  Music,
  Type,
  Star,
  Code,
  MousePointer,
  FormInput,
  FileText,
  ListOrdered,
  List,
  Quote,
  Minus,
  Tag,
  Space,
  Table,
  PanelTop,
  Layers,
  CreditCard,
  Square,
  CircleDot,
  Send,
  ListChecks,
} from "lucide-react";

export const elements: {
  label: string;
  id: ElementTypes;
  group: "layout" | "element";
  category: CategoryTypes;
  icon: LucideIcon;
}[] = [
  // Layout
  { label: "Container", id: "container", group: "layout", category: "Container", icon: SquareDashed },
  { label: "Section", id: "section", group: "layout", category: "Container", icon: SquareDashed },
  { label: "2 Columns", id: "2Col", group: "layout", category: "Container", icon: Columns2 },
  { label: "3 Columns", id: "3Col", group: "layout", category: "Container", icon: Columns3 },
  { label: "2 Rows", id: "2Row", group: "layout", category: "Container", icon: Rows },
  { label: "3 Rows", id: "3Row", group: "layout", category: "Container", icon: Rows },
  { label: "Header + 2 Cols", id: "Header2Col", group: "layout", category: "Container", icon: LayoutTemplate },
  { label: "2 Cols + Footer", id: "2ColFooter", group: "layout", category: "Container", icon: LayoutTemplate },
  { label: "Sidebar + 2 Rows", id: "Sidebar2Row", group: "layout", category: "Container", icon: Sidebar },
  { label: "2x2 Grid", id: "Grid2x2", group: "layout", category: "Container", icon: Grid2x2 },
  { label: "Layout 1", id: "Layout1", group: "layout", category: "Container", icon: Layout },
  { label: "Layout 2", id: "Layout2", group: "layout", category: "Container", icon: Layout },
  { label: "Layout 3", id: "Layout3", group: "layout", category: "Container", icon: Layout },
  { label: "Layout 4", id: "Layout4", group: "layout", category: "Container", icon: Layout },
  { label: "Layout 5", id: "Layout5", group: "layout", category: "Container", icon: Layout },
  { label: "Layout 6", id: "Layout6", group: "layout", category: "Container", icon: Layout },
  { label: "Layout 7", id: "Layout7", group: "layout", category: "Container", icon: Grid3x3 },
  { label: "Layout 8", id: "Layout8", group: "layout", category: "Container", icon: LayoutTemplate },
  // Text
  { label: "Heading 1", id: "h1", group: "element", category: "Text", icon: Heading1 },
  { label: "Heading 2", id: "h2", group: "element", category: "Text", icon: Heading2 },
  { label: "Heading 3", id: "h3", group: "element", category: "Text", icon: Heading3 },
  { label: "Heading 4", id: "h4", group: "element", category: "Text", icon: Heading4 },
  { label: "Heading 5", id: "h5", group: "element", category: "Text", icon: Heading5 },
  { label: "Heading 6", id: "h6", group: "element", category: "Text", icon: Heading6 },
  { label: "Paragraph", id: "p", group: "element", category: "Text", icon: Pilcrow },
  { label: "Span", id: "span", group: "element", category: "Text", icon: Text },
  // Media
  { label: "Image", id: "image", group: "element", category: "Basic", icon: Image },
  { label: "Video", id: "video", group: "element", category: "Media", icon: Video },
  { label: "Audio", id: "audio", group: "element", category: "Media", icon: Music },
  { label: "Marquee", id: "marquee", group: "element", category: "Media", icon: Type },
  { label: "Icon", id: "icon", group: "element", category: "Media", icon: Star },
  { label: "Embed", id: "embed", group: "element", category: "Media", icon: Code },
  // Interactive
  { label: "Link", id: "link", group: "element", category: "Link", icon: Link },
  { label: "Button", id: "button", group: "element", category: "Basic", icon: MousePointer },
  { label: "Form", id: "form", group: "layout", category: "Form", icon: FormInput },
  { label: "Input", id: "input", group: "element", category: "Form", icon: FormInput },
  { label: "Textarea", id: "textarea", group: "element", category: "Form", icon: FileText },
  { label: "Select", id: "select", group: "element", category: "Form", icon: ListChecks },
  { label: "Checkbox", id: "checkbox", group: "element", category: "Form", icon: Square },
  { label: "Radio", id: "radio", group: "element", category: "Form", icon: CircleDot },
  { label: "Submit", id: "submitButton", group: "element", category: "Form", icon: Send },
  // Content
  { label: "Ordered List", id: "ol", group: "element", category: "Content", icon: ListOrdered },
  { label: "Unordered List", id: "ul", group: "element", category: "Content", icon: List },
  { label: "List Item", id: "li", group: "element", category: "Content", icon: List },
  { label: "Blockquote", id: "blockquote", group: "element", category: "Content", icon: Quote },
  { label: "Code", id: "code", group: "element", category: "Content", icon: Code },
  { label: "Divider", id: "hr", group: "element", category: "Content", icon: Minus },
  { label: "Badge", id: "badge", group: "element", category: "Content", icon: Tag },
  { label: "Spacer", id: "spacer", group: "element", category: "Content", icon: Space },
  // Structure
  { label: "Table", id: "table", group: "element", category: "Content", icon: Table },
  { label: "Accordion", id: "accordion", group: "element", category: "Content", icon: PanelTop },
  { label: "Tabs", id: "tabs", group: "element", category: "Content", icon: Layers },
  { label: "Card", id: "card", group: "element", category: "Content", icon: CreditCard },
];
